### ISSUE TITLE
Proper source code lines shown in stack traces? 

### ISSUE THREAD

**Issue by mmc41** [arranbartish/angular-cli-seed#48]
I haven't got this seed to work exactly as-is because of bug #47 but when I try to pick out the pieces I want (chai) I got something basic working but assertions errors shows stacktraces pointing to transpiled code rather than the real source code. Is that something this full seed supports?

**Comment by arranbartish** [comment]
Hi, 

Yes, we managed to get the project running with all tests using karma/wallaby + mocha + chai and protractor + mocha + chai. 

Travis seems to agree with #47. It looks like over the last few months some dependencies have changed and we broke, I'll see what I can do.

**Comment by arranbartish** [comment]
Going to close this in favour of #47
